### PR TITLE
added rust support

### LINKED ISSUE #13: Add rust support

### PR DESCRIPTION
**Pull request by cocoa-xu**
Hi @nihui, this PR adds python support for ruapu. It should close #13 /

### CODE REVIEW

**Comment by nihui** [comment]
The glue that binds two languages is mixed in C
Let's move them into their own folders

```
|ruapu.h
|main.c
|
|python+
|      |ruapu-binding.c
|      |pyproject.toml
|
|rust+
|    |Cargo.toml
|    |lib.rs
```

**Comment by nihui** [comment]
> > The glue that binds two languages is mixed in C Let's move them into their own folders
> > ```
> > |ruapu.h
> > |main.c
> > |
> > |python+
> > |      |ruapu-binding.c
> > |      |pyproject.toml
> > |
> > |rust+
> > |    |Cargo.toml
> > |    |lib.rs
> > ```
> 
> No problem! It's done now~ Although I'm not quite sure which option I should use to specify the location of the `pyproject.toml` file in the `pypa/cibuildwheel` step in `pypi.yml`...

pypa/cibuildwheel has some options

```
  package-dir:
    description: 'Input directory, defaults to "."'
    required: false
    default: .
  output-dir:
    description: 'Folder to place the outputs in, defaults to "wheelhouse"'
    required: false
    default: wheelhouse
  config-file:
    description: 'File containing the config, defaults to {package}/pyproject.toml'
    required: false
    default: ''
```

**Comment by cocoa-xu** [comment]
`ruapu::rua()` is added to the Rust binding. I'll leave the python one in #51 
/cc @Yoh-Z

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
