### PR TITLE
added freebsd, netbsd and openbsd support

### LINKED ISSUE #27: Add FreeBSD support

### PR DESCRIPTION
**Pull request by cocoa-xu**
Hi this PR adds FreeBSD, NetBSD and OpenBSD support. It should close #27.

### CODE REVIEW

**Comment by nihui** [comment]
Hello, please append them to the table OS section at the beginning of the readme, thank you

**Comment by cocoa-xu** [comment]
Weird that vmactions are not working. Maybe remove these ci for now?

**Comment by nihui** [comment]
lgtm

**Comment by nihui** [comment]
Thanks for your contribution !

**Pull request merged**
